"""empty message

Revision ID: 8aee1150c3ce
Revises: 
Create Date: 2022-06-05 13:55:17.114798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aee1150c3ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('name', sa.String(length=150), nullable=False))
    op.add_column('contact', sa.Column('email', sa.String(length=200), nullable=True))
    op.add_column('contact', sa.Column('style', sa.String(length=200), nullable=True))
    op.add_column('contact', sa.Column('isbn', sa.String(length=100), nullable=True))
    op.alter_column('contact', 'title',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.drop_column('contact', 'ISBN')
    op.drop_column('contact', 'length')
    op.drop_column('contact', 'type')
    op.drop_column('contact', 'year_published')
    op.add_column('user', sa.Column('first_name', sa.String(length=150), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=150), nullable=True))
    op.add_column('user', sa.Column('style', sa.String(length=150), nullable=False))
    op.add_column('user', sa.Column('isbn', sa.String(length=150), nullable=False))
    op.add_column('user', sa.Column('email', sa.String(length=150), nullable=False))
    op.drop_column('user', 'ISBN')
    op.drop_column('user', 'length')
    op.drop_column('user', 'type')
    op.drop_column('user', 'year_published')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('year_published', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('type', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('length', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('ISBN', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('user', 'email')
    op.drop_column('user', 'isbn')
    op.drop_column('user', 'style')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.add_column('contact', sa.Column('year_published', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('contact', sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('contact', sa.Column('length', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('contact', sa.Column('ISBN', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.alter_column('contact', 'title',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.drop_column('contact', 'isbn')
    op.drop_column('contact', 'style')
    op.drop_column('contact', 'email')
    op.drop_column('contact', 'name')
    # ### end Alembic commands ###
